apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-with-k8s-development
spec:
  selector:
    matchLabels:
      app: spring-boot-with-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-with-k8s
    spec:
      containers:
        - name: spring-boot-with-k8s
          image: supto764/spring-boot-with-k8s:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
